/**
 * Mock data for development and demonstration
 * Used as fallback when database is unavailable
 */

export const mockCategories = [
  { slug: 'amateur', name: 'Amateur', description: 'Amateur content', videoCount: 245, order: 1 },
  { slug: 'professional', name: 'Professional', description: 'Professional studio content', videoCount: 189, order: 2 },
  { slug: 'milf', name: 'MILF', description: 'Mature content', videoCount: 156, order: 3 },
  { slug: 'teen', name: 'Teen (18+)', description: 'Young adult content (18+)', videoCount: 312, order: 4 },
  { slug: 'asian', name: 'Asian', description: 'Asian content', videoCount: 198, order: 5 },
  { slug: 'ebony', name: 'Ebony', description: 'Ebony content', videoCount: 145, order: 6 },
  { slug: 'latina', name: 'Latina', description: 'Latina content', videoCount: 167, order: 7 },
  { slug: 'blonde', name: 'Blonde', description: 'Blonde content', videoCount: 234, order: 8 },
  { slug: 'brunette', name: 'Brunette', description: 'Brunette content', videoCount: 256, order: 9 },
  { slug: 'redhead', name: 'Redhead', description: 'Redhead content', videoCount: 98, order: 10 },
  { slug: 'big-tits', name: 'Big Tits', description: 'Big tits content', videoCount: 289, order: 11 },
  { slug: 'anal', name: 'Anal', description: 'Anal content', videoCount: 178, order: 12 },
]

export const mockModels = [
  {
    slug: 'emma-stone',
    name: 'Emma Stone',
    avatar: null,
    bio: 'Popular content creator with a dedicated following',
    verified: true,
    country: 'USA',
    age: 28,
    height: '5\'7"',
    measurements: '34-24-36',
    hairColor: 'Brown',
    eyeColor: 'Green',
    videoCount: 45,
    views: 2500000,
    subscribers: 15000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'sophia-lee',
    name: 'Sophia Lee',
    avatar: null,
    bio: 'Asian beauty known for her elegant performances',
    verified: true,
    country: 'South Korea',
    age: 25,
    height: '5\'4"',
    measurements: '32-23-34',
    hairColor: 'Black',
    eyeColor: 'Brown',
    videoCount: 38,
    views: 1800000,
    subscribers: 12000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'maria-garcia',
    name: 'Maria Garcia',
    avatar: null,
    bio: 'Latina sensation with passionate performances',
    verified: true,
    country: 'Colombia',
    age: 27,
    height: '5\'6"',
    measurements: '36-26-38',
    hairColor: 'Black',
    eyeColor: 'Brown',
    videoCount: 52,
    views: 3200000,
    subscribers: 18000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'ashley-jones',
    name: 'Ashley Jones',
    avatar: null,
    bio: 'Blonde bombshell from California',
    verified: false,
    country: 'USA',
    age: 24,
    height: '5\'8"',
    measurements: '34-25-35',
    hairColor: 'Blonde',
    eyeColor: 'Blue',
    videoCount: 28,
    views: 950000,
    subscribers: 8000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'jasmine-black',
    name: 'Jasmine Black',
    avatar: null,
    bio: 'Ebony goddess with an incredible presence',
    verified: true,
    country: 'UK',
    age: 29,
    height: '5\'9"',
    measurements: '36-25-38',
    hairColor: 'Black',
    eyeColor: 'Brown',
    videoCount: 41,
    views: 2100000,
    subscribers: 14000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'maya-red',
    name: 'Maya Red',
    avatar: null,
    bio: 'Fiery redhead from Ireland',
    verified: false,
    country: 'Ireland',
    age: 23,
    height: '5\'5"',
    measurements: '32-24-34',
    hairColor: 'Red',
    eyeColor: 'Green',
    videoCount: 22,
    views: 680000,
    subscribers: 5500,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'anna-white',
    name: 'Anna White',
    avatar: null,
    bio: 'European beauty with classic elegance',
    verified: true,
    country: 'Germany',
    age: 26,
    height: '5\'7"',
    measurements: '34-24-35',
    hairColor: 'Blonde',
    eyeColor: 'Blue',
    videoCount: 35,
    views: 1500000,
    subscribers: 11000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
  {
    slug: 'lily-chen',
    name: 'Lily Chen',
    avatar: null,
    bio: 'Petite Asian with a captivating personality',
    verified: true,
    country: 'China',
    age: 22,
    height: '5\'2"',
    measurements: '30-22-32',
    hairColor: 'Black',
    eyeColor: 'Brown',
    videoCount: 48,
    views: 2800000,
    subscribers: 16000,
    socialLinks: { twitter: null, instagram: null, website: null, onlyfans: null },
  },
]

export const mockProducers = [
  {
    slug: 'studio-x',
    name: 'Studio X',
    logo: null,
    banner: null,
    description: 'Premium content producer specializing in high-quality productions',
    website: 'https://example.com',
    email: 'contact@example.com',
    country: 'USA',
    foundedYear: 2015,
    videoCount: 156,
    views: 12000000,
    subscribers: 45000,
    verified: true,
  },
  {
    slug: 'passion-films',
    name: 'Passion Films',
    logo: null,
    banner: null,
    description: 'Artistic adult entertainment with cinematic quality',
    website: 'https://example.com',
    email: 'contact@example.com',
    country: 'France',
    foundedYear: 2018,
    videoCount: 89,
    views: 8500000,
    subscribers: 32000,
    verified: true,
  },
  {
    slug: 'reality-kings',
    name: 'Reality Kings',
    logo: null,
    banner: null,
    description: 'Reality-based content with authentic performances',
    website: 'https://example.com',
    email: 'contact@example.com',
    country: 'USA',
    foundedYear: 2010,
    videoCount: 234,
    views: 25000000,
    subscribers: 78000,
    verified: true,
  },
  {
    slug: 'vixen-media',
    name: 'Vixen Media',
    logo: null,
    banner: null,
    description: 'High-end production with luxury aesthetics',
    website: 'https://example.com',
    email: 'contact@example.com',
    country: 'USA',
    foundedYear: 2016,
    videoCount: 112,
    views: 15000000,
    subscribers: 55000,
    verified: true,
  },
]

// Generate mock videos dynamically
export const mockVideos = Array.from({ length: 50 }, (_, index) => {
  const categoryIndex = index % mockCategories.length
  const modelIndex = index % mockModels.length
  const producerIndex = index % mockProducers.length
  
  return {
    id: `video-${index + 1}`,
    slug: `sample-video-${index + 1}`,
    title: `Professional Video ${index + 1} - Premium Quality Content`,
    description: 'High-quality premium content featuring professional performances. This video showcases exceptional production value and engaging content for discerning viewers.',
    thumbnail: null,
    videoUrl: '',
    duration: Math.floor(Math.random() * 1800) + 300,
    quality: ['4K', '1080p', '720p'][Math.floor(Math.random() * 3)],
    views: Math.floor(Math.random() * 500000) + 10000,
    likes: Math.floor(Math.random() * 10000) + 100,
    status: 'published',
    categories: [mockCategories[categoryIndex]],
    models: [mockModels[modelIndex]],
    producer: mockProducers[producerIndex],
    tags: ['premium', 'professional', 'exclusive'],
    createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
    publishedAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
  }
})
