#!/bin/bash
# Backblaze B2 + Cloudflare CDN Setup Script
# Run these commands to complete the setup

echo "=========================================="
echo "Step 1: Set Cloudflare Pages Secrets"
echo "=========================================="
echo "Run these commands (one at a time):"
echo ""
echo "wrangler pages secret put B2_KEY_ID"
echo "# Then paste: 005eaf89f218f5300000001"
echo ""
echo "wrangler pages secret put B2_APPLICATION_KEY"
echo "# Then paste: K005hTeSKlGbaFja5KCc7lQaHYMG7w"
echo ""
echo "wrangler pages secret put B2_BUCKET_ID"
echo "# Then paste: 5e9a7f08c93f220198bf0513"
echo ""
echo ""
echo "=========================================="
echo "Step 2: Cloudflare DNS Configuration"
echo "=========================================="
echo "Go to: Cloudflare Dashboard > Your Domain > DNS"
echo ""
echo "Add this CNAME record:"
echo "  Name: cdn"
echo "  Target: xpandorax-com.s3.us-east-005.backblazeb2.com"
echo "  Proxy: Enabled (Orange Cloud)"
echo ""
echo ""
echo "=========================================="
echo "Step 3: Cloudflare Cache Rules"
echo "=========================================="
echo "Go to: Cloudflare Dashboard > Rules > Cache Rules"
echo ""
echo "Create a rule:"
echo "  If: (cf.request.uri.path matches \"^/pictures/\") OR (cf.request.uri.path matches \"^/videos/\")"
echo "  Then:"
echo "    - Cache Level: Cache Everything"
echo "    - Edge Cache TTL: 1 year"
echo "    - Browser Cache TTL: 1 year"
echo ""
echo ""
echo "=========================================="
echo "Step 4: Test Locally"
echo "=========================================="
echo "Run: npm run dev"
echo "Then upload an image through Sanity Studio at http://localhost:5173"
echo "Check that it saves to B2 and returns a CDN URL"
echo ""
echo "Done!"
